### ISSUE TITLE
ImportError: cannot import name functools

### ISSUE THREAD

**Issue by Bystroushaak** [RobRuana/pockets#2]
Hi.

I have this error with freshly cloned repository, with ``six1.9``:

```python
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pockets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pockets/__init__.py", line 23, in <module>
    from pockets.inspect import resolve
  File "pockets/inspect.py", line 11, in <module>
    from six import functools, string_types
ImportError: cannot import name functools
```

**Comment by ftobia** [comment]
Hmm. I tried this with a fresh checkout and I did not see the same error you're seeing.

Can you do:

    >>> import six
    >>> six.__version__

for me? Doing `from six import functools` works on six==1.9, 1.8, 1.7, and does not work on 1.0 (the only versions I have tried).

That said, I think the functools import within six is incidental, and not part of the public api. I'll comment on your PR.

**Comment by Bystroushaak** [comment]
Well, this is strange. Output from ``.__version__``:

```python
>>> import six
>>> six.__version__
'1.5.2'
```

but at the same time output from ``pip``:

```sh
$ pip search six
six                       - Python 2 and 3 compatibility utilities
  INSTALLED: 1.9.0 (latest)
```

**Comment by Bystroushaak** [comment]
Oh, I see where is the problem - I am using Linux mint (ubuntu based), which installed package using aptitude into path with higher precedence. Aptitude package ``python-six`` is in 1.5.2-1 version (http://packages.ubuntu.com/trusty/python-six).

**Comment by Bystroushaak** [comment]
Also the package ``python-six`` from aptitude is basically unremovable, because it wants to take a lot of dependencies with it.

**Comment by RobRuana** [comment]
Ok, I've merged the pull request that fixes this issue. Additionally, I've lowered the required version of six to 1.5.2. There's a new version, 0.2.4, available on [pypi](https://pypi.python.org/pypi/pockets/0.2.4) that contains these updates.

Thanks, everybody!

**Comment by Bystroushaak** [comment]
Thanks.
